version: '3.8'

services:
  pos-db:
    image: postgres:16-alpine
    container_name: pos-pg-dev
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=SuperSecurePosDB!2026
      - POSTGRES_DB=ikonex_db
      - TZ=Africa/Nairobi
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  pg-data:
    name: pos-pg-data
